apiVersion: v1
kind: Namespace
metadata:
  name: citi-publiccloud-training

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: citi-publiccloud-training-cluster-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: citi-publiccloud-training
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: Secret
metadata:
  name: citi-publiccloud-training-account-token
  namespace: citi-publiccloud-training
type: Opaque
data:
  DELEGATE_TOKEN: "NDA1MTY0YjgzMDBlYjRiZTI2MzEwNDIzNTg4M2Q3ZjM="

---

# If delegate needs to use a proxy, please follow instructions available in the documentation
# https://ngdocs.harness.io/article/5ww21ewdt8-configure-delegate-proxy-settings

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    harness.io/name: citi-publiccloud-training
  name: citi-publiccloud-training
  namespace: citi-publiccloud-training
spec:
  replicas: 1
  selector:
    matchLabels:
      harness.io/name: citi-publiccloud-training
  template:
    metadata:
      labels:
        harness.io/name: citi-publiccloud-training
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3460"
        prometheus.io/path: "/api/metrics"
    spec:
      terminationGracePeriodSeconds: 600
      restartPolicy: Always
      containers:
      - image: harness/delegate:23.02.78500
        imagePullPolicy: Always
        name: delegate
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: "2048Mi"
          requests:
            cpu: "0.5"
            memory: "2048Mi"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3460
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/health
            port: 3460
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 15
        envFrom:
        - secretRef:
            name: citi-publiccloud-training-account-token
        env:
        - name: JAVA_OPTS
          value: "-Xms64M"
        - name: ACCOUNT_ID
          value: IFG41DWvSnaRLOVNB2uesg
        - name: MANAGER_HOST_AND_PORT
          value: https://workshop.harness.io/gratis
        - name: DEPLOY_MODE
          value: KUBERNETES
        - name: DELEGATE_NAME
          value: citi-publiccloud-training
        - name: DELEGATE_TYPE
          value: "KUBERNETES"
        - name: DELEGATE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INIT_SCRIPT
          value: |-
              microdnf install unzip
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              ./aws/install    
              aws --version
              curl -O -L https://releases.hashicorp.com/terraform/1.3.5/terraform_1.3.5_linux_amd64.zip
              unzip terraform_1.3.5_linux_amd64.zip
              mv ./terraform /usr/bin/
              terraform --version
        - name: DELEGATE_DESCRIPTION
          value: ""
        - name: DELEGATE_TAGS
          value: ""
        - name: NEXT_GEN
          value: "true"
        - name: CLIENT_TOOLS_DOWNLOAD_DISABLED
          value: "true"
        - name: LOG_STREAMING_SERVICE_URL
          value: "https://app.harness.io/gratis/log-service/"

---

apiVersion: v1
kind: Service
metadata:
  name: delegate-service
  namespace: citi-publiccloud-training
spec:
  type: ClusterIP
  selector:
    harness.io/name: citi-publiccloud-training
  ports:
    - port: 8080

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: upgrader-cronjob
  namespace: citi-publiccloud-training
rules:
  - apiGroups: ["batch", "apps", "extensions"]
    resources: ["cronjobs"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: citi-publiccloud-training-upgrader-cronjob
  namespace: citi-publiccloud-training
subjects:
  - kind: ServiceAccount
    name: upgrader-cronjob-sa
    namespace: citi-publiccloud-training
roleRef:
  kind: Role
  name: upgrader-cronjob
  apiGroup: ""

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: upgrader-cronjob-sa
  namespace: citi-publiccloud-training

---

apiVersion: v1
kind: Secret
metadata:
  name: citi-publiccloud-training-upgrader-token
  namespace: citi-publiccloud-training
type: Opaque
data:
  UPGRADER_TOKEN: "NDA1MTY0YjgzMDBlYjRiZTI2MzEwNDIzNTg4M2Q3ZjM="

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: citi-publiccloud-training-upgrader-config
  namespace: citi-publiccloud-training
data:
  config.yaml: |
    mode: Delegate
    dryRun: false
    workloadName: citi-publiccloud-training
    namespace: citi-publiccloud-training
    containerName: delegate
    delegateConfig:
      accountId: IFG41DWvSnaRLOVNB2uesg
      managerHost: https://workshop.harness.io/gratis

---

apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    harness.io/name: citi-publiccloud-training-upgrader-job
  name: citi-publiccloud-training-upgrader-job
  namespace: citi-publiccloud-training
spec:
  schedule: "0 */1 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 20
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: upgrader-cronjob-sa
          restartPolicy: Never
          containers:
          - image: harness/upgrader:latest
            name: upgrader
            imagePullPolicy: Always
            envFrom:
            - secretRef:
                name: citi-publiccloud-training-upgrader-token
            volumeMounts:
              - name: config-volume
                mountPath: /etc/config
          volumes:
            - name: config-volume
              configMap:
                name: citi-publiccloud-training-upgrader-config
